name: openfootball
description: Flutter client api for Open Football Data.
version: 0.1.0
repository: https://github.com/tupy/openfootball-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.3
  http: ^0.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.2

# The following section is specific to Flutter.
flutter:

